import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './styles/global.css'
import '@mantine/core/styles.css'

import { MantineProvider } from '@mantine/core'
import AuthProvider from '@/shared/auth/AuthProvider';
import { ChatContextProvider } from '@/context/ChatContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider>
          <AuthProvider>
            <ChatContextProvider>
              {children}
            </ChatContextProvider>
          </AuthProvider>
        </MantineProvider>
      </body>
    </html>
  )
}
